wip

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,7 +3,7 @@
 echo "Current directory: $(pwd)"
 # exit 0
 
-# リンターの実行
+# golangci-lint の実行
 echo ""
 echo "_____________________________________"
 echo "Running golangci-lint..."
@@ -14,7 +14,7 @@ if [ $? -ne 0 ]; then
 	exit 1
 fi
 
-# staticcheckの実行
+# staticcheck の実行
 echo ""
 echo "_____________________________________"
 echo "Running staticcheck..."
@@ -24,7 +24,17 @@ if [ $? -ne 0 ]; then
 	exit 1
 fi
 
-# セキュリティチェックの実行
+# deadcode の実行
+echo ""
+echo "_____________________________________"
+echo "Running deadcode..."
+make deadcode
+if [ $? -ne 0 ]; then
+	echo "deadcode failed. Commit aborted."
+	exit 1
+fi
+
+# gosec の実行
 echo ""
 echo "_____________________________________"
 echo "Running gosec..."
